name: Test Mac Demo Run

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup R 4.3.3
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Download portable library
        uses: actions/download-artifact@v4
        with:
          name: R_lib_mac
          path: M2_Demo_macOS

      - name: Unzip library
        run: |
          cd M2_Demo_macOS
          unzip R_lib_mac.zip

      - name: Run demo script
        run: |
          export R_LIBS_USER="$PWD/M2_Demo_macOS/_R_lib_mac"
          echo "30 10 5 400 110 NA NA" | Rscript M2_Demo_macOS/scripts/main.R
